# .github/FUNDING.yml

# GitHub Sponsors (list your username or organization name)
github: [Aktharnvdv]

# Patreon (just the username)
patreon: akthercmr

# Buy Me a Coffee (just the username)
buy_me_a_coffee: akthercmr

# Custom URLs (for anything else, like PayPal or a personal website)
custom: ["https://www.paypal.me/Aktharnvdv"]
