# .github/FUNDING.yml

# GitHub Sponsors (list your username or organization name)
github: [Aktharnvdv]

# Patreon (just the username)
patreon: your_patreon_username

# Open Collective (just the collective name)
open_collective: your_collective_name

# Ko-fi (just the username)
ko_fi: your_kofi_username

# Buy Me a Coffee (just the username)
buy_me_a_coffee: your_bmac_username

# Custom URLs (for anything else, like PayPal or a personal website)
custom: ["https://www.paypal.me/yourname", "https://yourwebsite.com/donate"]
